name = "parvathi";
console.log(name);
touppercaseName = name.toUpperCase();
console.log(touppercaseName);
tolowercaseName = name.toLowerCase();
console.log(tolowercaseName);
firstchar = name.charAt(0);
console.log(firstchar);
lastchar = name.charAt(name.length - 1);
console.log(lastchar);
lengthofstring = name.length;
console.log(lengthofstring);
includeschar = name.includes("a");
console.log(includeschar);
indexofchar = name.indexOf("v");
console.log(indexofchar);
substringname = name.substring(1, 4);
console.log(substringname);
splitname = name.split("");
console.log(splitname);
trimmedname = "   parvathi    ".trim();
console.log(trimmedname);
replacedname = name.replace("p","p");
console.log(replacedname);
repeatname = name.repeat(3);
console.log(repeatname);
